[package]
name = "contracts"
edition = "2024.beta"
license = "MIT"
authors = ["Inkray Team"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.54.0" }
Walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/walrus", rev = "main" }                         # example; pin to the latest testnet tag

[addresses]
contracts = "0x0"

[dev-dependencies]

[dev-addresses]
